# Greedee Config

listen = "127.0.0.1"
port = 9223

[basic_auth]
active = true
accounts = [
  "user:pass",
]

# Metrics Plugins

[graphite_plugin]
active = false
host = "127.0.0.1"
port = 2003
proto = "tcp"

[console_plugin]
active = true
json = false

# Events plugins

[mysql_plugin]
active = false
host = "127.0.0.1"
port = 3306
user = "myuser"
password = "p@ssw0rd"
database = "events"

# Store plugin (default memstore)

[memstore_plugin]
active = true
